### ISSUE TITLE
Upon connection loss, base.Client.write() may enter an infinite loop & consume all available CPU

### ISSUE THREAD

**Issue by kiall** [microsoft/go-otel-audit#15]
Upon connection loss, base.Client.write() may enter an infinite loop & consume all available CPU.

When the connection to the remote audit server is broken, base.Client.write() will continuously requeue the same message forever, without replacing the connection until the next time an audit msg is Sent.

Below is a 60 second (wall clock) profile of a otherwise idle service where the TCP connection to the audit server was broken. This service is constrained to using a maximum of 0.5 of a CPU. The profile is dominated by the base.Client.sender() method consuming 29.5 seconds of CPU time - an infinite loop consuming essentially all available CPU.

![image](https://github.com/user-attachments/assets/7c2f9000-f14f-4126-ae32-2cb52c0ec13e)
 
Only upon the next audit record emission (which for low usage services, may be an extended period of time), do we see the connection being replaced:

> {"time":"2024-10-03T09:56:28.80139767Z","level":"INFO","msg":"replacing audit client connection: Attempt 1, wait interval 0s"}

https://github.com/microsoft/go-otel-audit/blob/f2703cd2812fd021535dc5d4f8f3ecdc48a24c9a/audit/base/base.go#L501C1-L523C2

**Comment by element-of-surprise** [comment]
Yeah, see the problem.

We are going to need a patch at the base client for the loop problem and another patch at the smart client so we don't wait for the next message to reset.

**Comment by element-of-surprise** [comment]
Regression test and fix added.  Waiting on my code reviewer.  

This will and in a 0.2.1 release.

**Comment by element-of-surprise** [comment]
This is now fixed.  Thanks for the bug request and follow ups.
